SELECT name FROM employee WHERE salary > 20000;
SELECT * FROM employee WHERE salary = 51000;
SELECT name, experience FROM employee WHERE age > 35;
SELECT * FROM employee WHERE profile='dev';
SELECT name FROM employee WHERE profile='test';
SELECT * FROM employee WHERE salary = 25000;
SELECT * FROM employee WHERE salary > 25000;
SELECT name,email FROM employee WHERE salary <> 51000;
UPDATE employee SET salary=salary+10000 WHERE experience<20;
DELETE FROM employee WHERE experience=21;
UPDATE employee SET salary=salary-21000 WHERE name='john';
ALTER TABLE employee ADD branch_location VARCHAR(50);
SELECT SUM(salary) AS total_salary FROM employee;
SELECT MAX(salary) FROM employee WHERE profile='test';
SELECT AVG(experience) FROM employee;
SELECT name FROM employee WHERE salary=(SELECT MAX(salary) FROM employee);
SELECT name,experience FROM employee WHERE salary=(SELECT MIN(salary) FROM employee);
SELECT COUNT(*) FROM employee;
SELECT name FROM employee WHERE profile='test' AND salary>25000;
UPDATE employee SET profile='support' WHERE name='radha';
SELECT MAX(salary) FROM employee WHERE salary<(SELECT MAX(salary) FROM employee);
SELECT MIN(salary) FROM employee WHERE salary>(SELECT MIN(salary) FROM employee);
SELECT AVG(salary) FROM employee WHERE profile='dev';
SELECT name,salary FROM employee WHERE experience=(SELECT MIN(experience) FROM employee);
SELECT name FROM employee WHERE age=(SELECT MIN(age) FROM employee);
DELETE FROM employee;